export default {
    NOTIFICATION:{
        DELETE:'DELETE!',
        SUCCESS:'SUCCESS!'
    }
}
export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";
export const API_CALL_DELETE_REQUEST = "API_CALL_DELETE_REQUEST";
export const API_CALL_DELETE_SUCCESS = "API_CALL_DELETE_SUCCESS";
export const API_CALL_DELETE_FAILURE = "API_CALL_DELETE_FAILURE";
export const API_CALL_EDIT_REQUEST = "API_CALL_EDIT_REQUEST";
export const API_CALL_EDIT_SUCCESS = "API_CALL_EDIT_SUCCESS";
export const API_CALL_EDIT_FAILURE = "API_CALL_EDIT_FAILURE";
export const API_CALL_SAVE_EDIT_REQUEST = "API_CALL_SAVE_EDIT_REQUEST";
export const API_CALL_SAVE_EDIT_SUCCESS = "API_CALL_SAVE_EDIT_SUCCESS";
export const API_CALL_SAVE_EDIT_FAILURE = "API_CALL_SAVE_EDIT_FAILURE";